unicornVersion: "0.1.0"
name: "Unicorn"
description: "\U0001f984 A tool to create, work on, test and deploy projects."
license: null
version: "0.1.0"
categorization:
  component:
    values:
      - name: "action"
        description: "GitHub Action related code"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/action/**"
      - name: "api"
        description: "DSL/Action/Template-API related code"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/api/**"
      - name: "commands"
        description: "Builtin commands"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/commands/**"
      - name: "console"
        description: "Console environment related code"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/console/**"
      - name: "core"
        description: "Core code"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/core/**"
      - name: "script"
        description: "Script DSL"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/script/**"
      - name: "template"
        description: "Template evaluation"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/template/**"
      - name: "templates"
        description: "Default templates"
        paths:
          - "templates/**"
      - name: "utils"
        description: "Utility code"
        paths:
          - "src/main/kotlin/com/jonaswanke/unicorn/utils/**"
    labels:
      color: "c2e0c6"
      prefix: "C: "
      descriptionPrefix: "Component: "
  priority:
    values:
      - name: "1"
        description: "1 (Lowest)"
      - name: "2"
        description: "2 (Low)"
      - name: "3"
        description: "3 (Medium)"
      - name: "4"
        description: "4 (High)"
      - name: "5"
        description: "5 (Highest)"
    labels:
      color: "e5b5ff"
      prefix: "P: "
      descriptionPrefix: "Priority: "
  type:
    values:
      - name: "feat"
        description: ":tada: New Features"
      - name: "change"
        description: "⚡ Changes"
      - name: "fix"
        description: ":bug: Bug Fixes"
      - name: "docs"
        description: ":scroll: Documentation updates"
      - name: "refactor"
        description: ":building_construction: Refactoring"
      - name: "build"
        description: ":package: Build & CI"
    labels:
      color: "c5def5"
      prefix: "T: "
      descriptionPrefix: "Type: "
