name: 'Unicorn Action'
author: 'Jonas Wanke <contact@wanke.dev>'
description: 'Check your PRs with 🦄 Unicorn'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: check
  color: purple
