description: |-
  Creates a simple dart package, based on base.
  (File source: https://github.com/dart-lang/stagehand/tree/master/templates/package-simple)
parameters:
    homepage:
        name: Homepage
        help: for pubspec.yaml; visible on pub.dev
        required: false
    author:
        name: Author name
        help: for pubspec.yaml; visible on pub.dev
        default: ${global.gitHub?.username}
    authorEmail:
        name: Author email address
        help: for pubspec.yaml; visible on pub.dev
        required: false
    minSdkVersion:
        name: Minimum Dart SDK version
        default: 2.5.0
dependsOn:
  - name: base
files:
  - from: pubspec.yaml.ftl
  - from: analysis_options.yaml
  - from: lib/package.dart.ftl
    to: lib/${project.name}.dart
  - from: lib/src/**
  - from: example/**
  - from: test/**
