description: Adds the project's license as ./LICENSE
parameters:
    company:
        name: Company
        help: Project owner/copyright holder
        default: ${global.gitHub?.username}
files:
  - from: ${project.license}.LICENSE.ftl
    to: LICENSE
    condition: project.license != null && project.license != License.NONE
