name: Unicorn

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize

jobs:
  unicorn:
    name: Unicorn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JonasWanke/unicorn@dev
        with:
          repo-token: "${{ secrets.UNICORN_TOKEN }}"
