name: Unicorn

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  unicorn:
    name: 🦄 Unicorn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JonasWanke/unicorn@v0.1
        with:
          repo-token: "${{ secrets.UNICORN_TOKEN }}"
